### PR TITLE
Update remote-working-resources.csv

### PR DESCRIPTION
**Pull request by oj-gh**
Adding a 4 day week job board to the mix

### CODE REVIEW

**Comment by georgemandis** [comment]
Thanks! Would you mind running `npm run build` and committing the files it changes?

**Comment by oj-gh** [comment]
Thank you. That should be done now.

**Comment by georgemandis** [comment]
Are you sure you ran it? I'd expect to see 3 files changes:
- Thie CSV
- The HTML file
- The Markdown file

**Comment by oj-gh** [comment]
Sorry this is taking up so much of your time. The csv seems to be updated in my fork https://github.com/oj-gh/remote-working-list/blob/main/remote-working-resources.csv so are the .html and .md files except the OPML as I didn't add RSS feed in the commit. The PR seems to be showing these changes too. Should I try again? 😁😁

**Comment by georgemandis** [comment]
Yeah, the other PR looks better! Just a couple dot files to  remove, but we can continue the conversation over there :)

I'll close this PR out.

**Pull request closed without merging**
