### PR TITLE
Update remote-working-resources.html

### PR DESCRIPTION
**Pull request by stefanwuthrich**
Fix Link golangjob.xyz

### CODE REVIEW

**Comment by georgemandis** [comment]
Thanks Stefan! Would you mind adding this to the CSV and OPML files as well?

**Comment by stefanwuthrich** [comment]
Tk you. Sure

**Comment by georgemandis** [comment]
Thanks! Would you mind combining those into just one PR?

**Comment by stefanwuthrich** [comment]
done

**Comment by georgemandis** [comment]
Looks good—thanks!

**Pull request merged**
