### PR TITLE
OkJob - remote & 4 day week jobs 

### PR DESCRIPTION
**Pull request by oj-gh**
Adding a 4 day week job board to the mix

### CODE REVIEW

**Comment by georgemandis** [comment]
Looks good, but would you mind removing the `.codesandbox` and `.devcontainer` files/folders?

**Comment by oj-gh** [comment]
All should be good now.

**Comment by georgemandis** [comment]
@oj-gh I know it's been... a minute. I'm still seeing those files here though. If you can remove them, I'll merge this!

**Comment by oj-gh** [comment]
Sorry should be good to go now. Thanks

**Pull request merged**
